#cloud-config

runcmd:
  - apt-get update
  - apt-get install -y haproxy

  - echo "==> Writing haproxy config..."
  - |
    cat > /etc/haproxy/haproxy.cfg <<'EOF'
${haproxy_config}
EOF

  - systemctl enable haproxy
  - systemctl restart haproxy